base.url=https://www.saucedemo.com/
page.timeout=10
element.timeout=10

# Browser options: chrome | firefox
browser=chrome

#headless options: false - windows is visible | true - window is hidden
headless=true


